logging:
  config: classpath:log4j2.xml

spring:
  profiles:
    active: dev
  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: HTML5
  cache:
    type: caffeine

server:
  port: 9368
  context-path: /
  undertow:
    accesslog:
      enabled: true
      pattern: "%t %I %q ‘%{i,X-Real-IP}/%a' %l %u %v '%r' %s '%b/%{o,Content-Length}' '%{o,Content-Type}' '%{i,User-Agent}' '%{i,Referer}'"
      dir: /opt/logs/wangqiqi/huaqi/access
      rotate: true
    buffer-size: 1024
    direct-buffers: true
    io-threads: 2
    worker-threads: 20
  session:
    timeout: 60  # session最大超时时间(分钟)，默认为30
  error:
    path: /404.html  # 错误页，指定发生错误时，跳转的URL

